In [34]:
#Importing needed libraries
import pandas as pd
import numpy as np
from scipy.linalg import inv

## Q1. Pandas version
What's the version of Pandas that you installed?

In [7]:
print(f"The pandas version installed is: {pd.__version__}")

The pandas version installed is: 2.1.4


## Getting the data

In [5]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-10-01 08:44:56--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291.58K  --.-KB/s    in 0.08s   

2024-10-01 08:44:57 (3.53 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [6]:
df = pd.read_csv('laptops.csv')
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


## Q2. Records count
How many records are in the dataset?

In [8]:
print(f"There are {len(df)} records in the dataset")

There are 2160 records in the dataset


## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [12]:
df['Brand'].unique()

array(['Asus', 'Alurin', 'MSI', 'HP', 'Lenovo', 'Medion', 'Acer', 'Apple',
       'Razer', 'Gigabyte', 'Dell', 'LG', 'Samsung', 'PcCom', 'Microsoft',
       'Primux', 'Prixton', 'Dynabook Toshiba', 'Thomson', 'Denver',
       'Deep Gaming', 'Vant', 'Innjoo', 'Jetwing', 'Millenium', 'Realme',
       'Toshiba'], dtype=object)

In [13]:
print(f"There are {df['Brand'].nunique()} laptop brands in the dataset")

There are 27 laptop brands in the dataset


## Q4. Missing values
How many columns in the dataset have missing values?

In [14]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [17]:
print(f"There are {df.isnull().any().sum()} columns in the dataset with missing values")

There are 3 columns in the dataset with missing values


## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [28]:
print(f"The maximum price for Dell notebooks in the dataset is: {df[df['Brand'] == 'Dell']['Final Price'].max()}")

The maximum price for Dell notebooks in the dataset is: 3936.0


## Q6. Median value of Screen
* Find the median value of Screen column in the dataset.
* Next, calculate the most frequent value of the same Screen column.
* Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
* Now, calculate the median value of Screen once again.

In [29]:
# Find the median value of Screen column in the dataset.
df['Screen'].median()

15.6

In [30]:
# Calculate the most frequent value of the same Screen column.
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [31]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step
df['Screen'].fillna(df['Screen'].mode()[0], inplace=True)

In [33]:
# Now, calculate the median value of Screen once again.
df['Screen'].median()

15.6

**Has it changed?**

Answer:  
No

## Q7. Sum of weights
* Select all the "Innjoo" laptops from the dataset.
* Select only columns RAM, Storage, Screen.
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To * get the transpose, use X.T. Let's call the result XTX.
* Compute the inverse of XTX.
* Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the sum of all the elements of the result?

In [37]:
# Select all the "Innjoo" laptops from the dataset.
df[df['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [38]:
# Select only columns RAM, Storage, Screen.
df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [40]:
# Get the underlying NumPy array. Let's call it X
X = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']].values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [41]:
# Compute matrix-matrix multiplication between the transpose of X and X. To * get the transpose, use X.T. Let's call the result XTX.
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [42]:
# Compute the inverse of XTX.
XTX_inverse = inv(XTX)
XTX_inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [44]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [45]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = XTX_inverse.dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [46]:
# What's the sum of all the elements of the result?
print(f"The sum of all elements in w is: {w.sum()}")

The sum of all elements in w is: 91.2998806299555
